### ISSUE TITLE
How do you write outputs to volumes and share outputs from one step to another?

### ISSUE THREAD

**Issue by tachyus-ryan** [argoproj-labs/hera-workflows#11]
I have several steps that write outputs. These could write to volumes or artifacts, and the files need to be shared. What's the recommended way to handle this? Is this handled implicitly by hera?

**Comment by rodrigobaron** [comment]
That's a good question, also wanna know about this. I've done one [POC](https://gist.github.com/rodrigobaron/7830c073aea3d7d37a761f8299f65f7d) which uses several tricks to be able train an random regressor.

btw this is using an [next_when](https://github.com/argoproj-labs/hera-workflows/pull/8) implementation.

**Comment by flaviuvadan** [comment]
> I have several steps that write outputs. These could write to volumes or artifacts, and the files need to be shared. What's the recommended way to handle this? Is this handled implicitly by hera?

Hey @tachyus-ryan! Thanks for another question 🙂 You can create a [Volume](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/v1/volume.py#L15), that is passed to a [Resources](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/v1/resources.py#L11) object, which is then passed to a [Task](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/v1/task.py#L89) in order to specify a volume. This volume can be shared between the resources of multiple tasks, which makes Argo Workflows provision a single volume that is then shared between tasks! Here's an example with results of Argo Workflows logs:
```python
from hera.v1.resources import Resources
from hera.v1.volume import Volume
from hera.v1.task import Task
from hera.v1.workflow import Workflow
from hera.v1.workflow_service import WorkflowService

def f(i: int):
    import os

    print(f'This is task: {i}')

    if i == 1:
        print('Adding stuff to /mnt/vol to test content in t2')
        with open('/mnt/vol/test.txt', 'w') as _f:
            _f.write('testing content from task 1')
    else:
        print(f"listdir output: {os.listdir('/mnt/vol')}")
        try:
            with open('/mnt/vol/test.txt', 'r') as _f:
                print(_f.read())
        except Exception as e:
            print(f'Hera is missing some features: {e}')

ws = WorkflowService('my-argo-server.com', 'my-argo-token')
w = Workflow('fv-testing')

v = Volume(size='5Gi', mount_path='/mnt/vol')
r = Resources(volume=v)

# you can use a different Resources object for each task but with the same volume
t1 = Task('t1', f, func_params=[{'i': 1}], resources=r)
t2 = Task('t2', f, func_params=[{'i': 2}], resources=r)
t1.next(t2)
w.add_tasks(t1, t2)
w.submit()
```
<img width="600" alt="Screen Shot 2021-11-04 at 23 32 51" src="https://user-images.githubusercontent.com/18152652/140453959-f13da9d2-ce5a-41ff-9f01-6fd240169ec9.png">
<img width="615" alt="Screen Shot 2021-11-04 at 23 33 16" src="https://user-images.githubusercontent.com/18152652/140453995-3141a4d4-d73c-4a2a-bbbe-7ddc22b21122.png">
<img width="633" alt="Screen Shot 2021-11-04 at 23 33 30" src="https://user-images.githubusercontent.com/18152652/140454018-56abf4e8-a454-4aad-afda-f46e356ad091.png">

This is the YAML template:
```yaml
- name: fv-testing-2924be2b
  inputs: {}
  outputs: {}
  metadata: {}
  dag:
    tasks:
      - name: t1
        template: t1
        arguments:
          parameters:
            - name: i
              value: '1'
      - name: t2
        template: t2
        arguments:
          parameters:
            - name: i
              value: '2'
        dependencies:
          - t1
  parallelism: 50
- name: t1
  inputs:
    parameters:
      - name: i
        value: '1'
  outputs: {}
  metadata: {}
  script:
    name: t1
    image: 'python:3.7'
    command:
      - python
    resources:
      limits:
        cpu: '4'
        memory: 16Gi
      requests:
        cpu: '4'
        memory: 16Gi
    volumeMounts:
      - name: c76b6c91-4bea-4865-ad3d-b2bfdc7d046d
        mountPath: /mnt/vol
    source: |
      import json
      i = json.loads('{{inputs.parameters.i}}')

      import os
      print(f'This is task: {i}')
      if i == 1:
          print('Adding stuff to /mnt/vol to test content in t2')
          with open('/mnt/vol/test.txt', 'w') as _f:
              _f.write('testing content from task 1')
      else:
          print(f"listdir: {os.listdir('/mnt/vol')}")
          with open('/mnt/vol/test.txt', 'r') as _f:
              print(_f.read())
- name: t2
  inputs:
    parameters:
      - name: i
        value: '2'
  outputs: {}
  metadata: {}
  script:
    name: t2
    image: 'python:3.7'
    command:
      - python
    resources:
      limits:
        cpu: '4'
        memory: 16Gi
      requests:
        cpu: '4'
        memory: 16Gi
    volumeMounts:
      - name: c76b6c91-4bea-4865-ad3d-b2bfdc7d046d
        mountPath: /mnt/vol
    source: |
      import json
      i = json.loads('{{inputs.parameters.i}}')

      import os
      print(f'This is task: {i}')
      if i == 1:
          print('Adding stuff to /mnt/vol to test content in t2')
          with open('/mnt/vol/test.txt', 'w') as _f:
              _f.write('testing content from task 1')
      else:
          print(f"listdir: {os.listdir('/mnt/vol')}")
          with open('/mnt/vol/test.txt', 'r') as _f:
              print(_f.read())
```
