### ISSUE TITLE
How to share context in a cronworkflow?

### ISSUE THREAD

**Issue by bnuzhanyu** [argoproj-labs/hera-workflows#118]
Suppose I have a cronworkflow to execute a hive sql each day, and do some further process.
```python
ws = CronWorkflowService(...)
w = CronWorkflow('cron-example', ws, namespace="argo")
t1 = Task(image='hive/image', command=f"hive -e 'select * from t where day={today} > savedpath_{today}")
t2 = Task( process file savedpath_{today} )
```
The sql is changing every day, so the t1.command is not determined while submitting the cronworkflow, and t2 should have same value for today.
Though I can use Workflow and submit each day, but is there any better way in hera?

I have been thinking use this way, but I don't know whether argo would support this.
```python
def context_gen():
    #return kv, only support standard lib
    today = datetime.date.today().format('%Y%m%d')
    return {
        "sql_command": f"hive -e 'select * from t where day={today}' > savedpath_{today}"
    }

w = CronWorkflow('cron-example', ws, namespace="argo", context_generator=context_gen)  
# when a new workflow start, it will new a task to generate the context, and passing to all other tasks
t1 = Task(image='hive/image', command_gen = from_context('sql_command') )
```

**Comment by flaviuvadan** [comment]
Hi @bnuzhanyu! Thank you for the question! I do not think Argo supports dynamically parametrizing the `command` that is run as part of a container/task but I think there are 2 ways to do this through Hera:
* Use the idea of dynamic fanout - make 2 tasks, one that creates the context, and one that uses the context:
```python
def ctx_gen():
    import datetime, json, sys

    today = datetime.date.today().format('%Y%m%d')
    json.dumps([{'ctx_cmd': f"hive -e 'select * from t where day={today}' > savedpath_{today}"}], sys.stdout)

def ctx_con(ctx_cmd):
    import os
    os.system(ctx_cmd).read()

w = CronWorkflow(...)
ctx_producer = Task('generate-ctx', ctx_gen)
ctx_consumer = Task('consume-ctx', ctx_con, input_from=InputFrom(name=ctx_producer.name, parameters=['ctx_cmd']), image='hive/image')
ctx_producer >> ctx_consumer
w.add_tasks(ctx_producer, ctx_consumer)
w.submit()
```

* Run the command in a task by itself using `os.system`: 
```python
def run_hive():
    import datetime, json, sys

    today = datetime.date.today().format('%Y%m%d')
    cmd = f"hive -e 'select * from t where day={today}' > savedpath_{today}"
    os.system(cmd).read()

w = CronWorkflow(...)
hive = Task('run-hive', ctx_gen, image='hive/image')
w.add_tasks(hive)
w.submit()
```

Would these work for your use case?

**Comment by flaviuvadan** [comment]
Got it, I feel like I better understand what the need is. This is supported in Argo via a fanout/fanin mechanism via parameters, like so:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fan-out-in-params-workflow-
spec:
  entrypoint: fan-out-in-params-workflow
  templates:

  # Definition of the entire workflow
  # You'll find the definition of the different step templates below.
  - name: fan-out-in-params-workflow
    steps:
    - - name: generate
        template: gen-number-list
    - - name: fan-out
        template: fan-out
        arguments:
          parameters:
          - name: number
            value: "{{item}}"
        # This line actually fans out the items into multiple steps
        withParam: "{{steps.generate.outputs.result}}"
    - - name: fan-in
        template: fan-in
        arguments:
          parameters:
          - name: numbers
            value: "{{steps.fan-out.outputs.parameters}}"

  # Step to generate the output sequence
  # The output is a simple JSON-compliant array of ints like so:
  # [1, 2, 3]
  - name: gen-number-list
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import sys
        json.dump([i for i in range(1, 4)], sys.stdout)
  # Fan-out: Splitting the output sequence into steps
  # Argo iterates over the array generated in the previous step and
  # passes on one element for each step.
  - name: fan-out
    inputs:
      parameters:
      - name: number
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.number}} > /tmp/number.txt"]
    outputs:
      parameters:
        - name: number
          valueFrom:
            path: /tmp/number.txt

  # Fan-in: Combining the outputs
  # When reading the elements, argo reads the output of the previous step
  # from "output-number" as JSON objects fo all output parameters. The input
  # to this step will then be a JSON-compliant array of objects like so:
  # [{"number":"1"},{"number":"2"},{"number":"3"}]
  #
  # Do note: The ints were converted into strings since argo considers all
  # inputs and outputs to be strings by default.
  - name: fan-in
    inputs:
      parameters:
        - name: numbers
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo received {{inputs.parameters.numbers}}"]
```
([source](https://medium.com/@corvin/dynamic-fan-out-and-fan-in-in-argo-workflows-d731e144e2fd)). So, I think Hera needs to support this because it's a case that is actually quite common and users may be forced to perform workarounds at the moment. I will mark this as an enhancement and try to work on it for v3!
