### ISSUE TITLE
How can I use MinIO for other namespace?

### ISSUE THREAD

**Issue by bnuzhanyu** [argoproj-labs/hera-workflows#119]
I submit a task in 'argo' namespace and works well, but got an error in another namespace.
```
Error (exit code 1): You need to configure artifact storage. More information on how to do this can be found in the docs: https://argoproj.github.io/argo-workflows/configure-artifact-repository/
```
I compared the yaml files, and found the spec.volumes are different. 

```
# in other namespace
spec:
  volumes:
    - name: var-run-argo
      emptyDir: {}
    - name: argo-staging
      emptyDir: {}
    - name: default-token-sxcsg
      secret:
        secretName: default-token-sxcsg
        defaultMode: 420

# in argo namespace
    - name: var-run-argo
      emptyDir: {}
    - name: my-minio-cred
      secret:
        secretName: my-minio-cred
        items:
          - key: accesskey
            path: accesskey
          - key: secretkey
            path: secretkey
        defaultMode: 420
```
https://argoproj.github.io/argo-workflows/configure-artifact-repository/ tells a way to solve,  but how can I get it work well for all namespaces when I install argo?
