### ISSUE TITLE
Global parameters for workflow templates

### ISSUE THREAD

**Issue by lambertsbennett** [argoproj-labs/hera-workflows#138]
Hi I am trying to set up a workflow template that can accept global parameters from Argo Events. 

When I create my workflow template using Hera I see the following:

```yaml
metadata:
  name: train-template
  namespace: argo
  uid: 6d42116f-3c0f-473e-8f5e-d7c0015e034d
  resourceVersion: '91607583'
  generation: 1
  creationTimestamp: '2022-04-19T07:56:20Z'
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-default
  managedFields:
    - manager: argo
      operation: Update
      apiVersion: argoproj.io/v1alpha1
      time: '2022-04-19T07:56:20Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:workflows.argoproj.io/creator': {}
        'f:spec': {}
spec:
  templates:
    - name: train-template
      inputs: {}
      outputs: {}
      metadata: {}
      dag:
        tasks:
          - name: echo-pvsystemid
            template: echo-pvsystemid
            arguments:
              parameters:
                - name: pvsystemid
                  value: '"this did not work"'
            continueOn: {}
      parallelism: 50
    - name: echo-pvsystemid
      inputs:
        parameters:
          - name: pvsystemid
            value: '"this did not work"'
      outputs: {}
      metadata: {}
      daemon: false
      script:
        name: echo-pvsystemid
        image: 'python:3.7'
        command:
          - python
        resources:
          limits:
            cpu: '1'
            memory: 4Gi
          requests:
            cpu: '1'
            memory: 4Gi
        imagePullPolicy: Always
        source: |
          import json
          pvsystemid = json.loads('''{{inputs.parameters.pvsystemid}}''')

          print(pvsystemid)
  entrypoint: train-template
  arguments: {}
```
Where there are no inputs for the train-template. Is there a way with Hera to specify a global input parameter?

**Comment by flaviuvadan** [comment]
Hi @lambertsbennett! Thanks for submitting the question. Also, thanks for writing a Medium blog that used Hera 🙂 do you mind sharing the Hera code you used? My guess is that `pvsystemid` is a parameter for a Python function and the value was set via the `func_params` field on a `Task`?

**Comment by lambertsbennett** [comment]
Yes exactly and no problem I'm a huge fan!

```python 
from hera.task import Task
from hera.workflow_template import WorkflowTemplate
from hera.workflow_template_service import WorkflowTemplateService


def echo_pvsystemid(pvsystemid: str):
    print(pvsystemid)

ws = WorkflowTemplateService(host='https://DOMAIN:2746', token=TOKEN, verify_ssl=False)
w = WorkflowTemplate('train-template', ws, namespace='argo')
echo = Task('echo-pvsystemid', echo_pvsystemid, [{'pvsystemid': 'Hello, world!'}])
w.add_tasks(echo)
w.create()
```
I've been able to pull off something very similar with YAML, but when I run this no matter what "Hello, world!" is printed and it ignores the parameter value obtained from the request body.

For completeness the Argo Events Sensor definition is here:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo
  dependencies:
    - name: train-trigger
      eventSourceName: webhook
      eventName: train
  triggers:
    - template:
        name: webhook-train-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: train-w-global-arg-
              spec:
                serviceAccountName: argo
                entrypoint: echo-pvsystemid
                arguments:
                  parameters:
                    - name: pvsystemid
                      value: hello
                templates:
                  - name: echo-pvsystemid
                    dag:
                      tasks:
                      - name: echo-pvsystemid
                        templateRef:
                          name: train-template
                          template: echo-pvsystemid
                      # - name: echo-random
                      #   templateRef:
                      #     name: train-template
                      #     template: echo-random
          parameters:
            - src:
                dependencyName: train-trigger
                dataKey: body.pvsystemid
              dest: spec.arguments.parameters.0.value
```

**Comment by flaviuvadan** [comment]
I have a hunch of what's going on. When parameters are created by Hera it sets a literal `value` on both the task parameters at the workflow level and at the template level, as can be seen [here](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/task.py#L580) and [here](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/task.py#L492). The [documentation](https://argoproj.github.io/argo-workflows/fields/#parameter) of `value` says: 
```
Value is the literal value to use for the parameter. If specified in the context of an input parameter, the value takes precedence over any passed values
```

Problem 1: the inputs should not have a value.

Now, your goal is to parametrize tasks based on global variables. These have a different access pattern, as documented [here](https://github.com/argoproj/argo-workflows/tree/master/examples#parameters). The global ones are accessed via `{{workflow.parameters.X}}`.

Problem 2: Hera does not currently support global parameters, and it needs to support both global and local (as arguments).

I attempted the global parameter usage using a modified workflow of [this Hera example](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/hello_hera.py). Here's the YAML:

```yaml
metadata:
  name: delightful-dragon
  namespace: default
spec:
  arguments:
    parameters:
      - name: x
        value: '"hello hera"'
  entrypoint: hello
  templates:
  - name: hello
    dag:
      tasks:
        - name: t
          template: t
          arguments:
            parameters:  
              - name: x
                value: "{{workflow.parameters.x}}"   # TODO: Hera needs to support specifying global parameters
    parallelism: 50
  - name: t
    inputs:
      parameters:
        - name: x  # TODO: Hera needs to remove the value/default of the input
    outputs: {}
    metadata: {}
    daemon: false
    script:
      name: t
      image: 'python:3.7'
      command:
        - python
      resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: '1'
          memory: 1Gi
      source: |
        import json
        x = json.loads('''{{inputs.parameters.x}}''')

        print(x)
```

So, I am inclined to mark the two things above as enhancements. Thoughts?

I also wanted to ask: could the `dest` field on the even be modified so that it injects a different part of the template? For instance, instead of `dest: spec.arguments.parameters.0.value`, could that be `dest: spec.templates.0.dag.tasks.0.arugments.parameters.0.value`?
