### ISSUE TITLE
Is it possible assign affinity field to workflow?

### ISSUE THREAD

**Issue by MichaelLan** [argoproj-labs/hera-workflows#153]
I'd like to add the affinity filed in the workflow spec, but in the docs and the code I don't find the correct way.

is it possible with Hera?

In my yaml I write this code, as indicated in the documentation [Affinity](https://argoproj.github.io/argo-workflows/fields/#affinity).

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node_group
              operator: In
              values:
                - argo-workflow
```
