### ISSUE TITLE
Get environment name from secretKeyRef within secrets

### ISSUE THREAD

**Issue by sarmientoj24** [argoproj-labs/hera-workflows#165]
I have these following parameters in my YAML file

```
  imagePullSecrets:
    - name: img-auth
...

env:
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: access-id
        key: access_key
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: origin-id
        key: access_key_id
  - name: AWS_DEFAULT_REGION
    value: us-east-2
```

I am not sure how to do this on hera-workflows
