### ISSUE TITLE
Using GPU K80 on Azure

### ISSUE THREAD

**Issue by sarmientoj24** [argoproj-labs/hera-workflows#169]
Hi! Great work!

Saw this code snippet for using GPU. But it seems to be for Google Cloud. I would like to use K80 from Azure.
```
gke_k80_gpu = {'cloud.google.com/gke-accelerator': 'nvidia-tesla-k80'}
d = Task(
    'do',
    do,
    image='horovod/horovod:0.22.1',
    resources=Resources(gpus=1),
    tolerations=[GPUToleration],
    node_selectors=gke_k80_gpu,
)
```

I would like to translate this
```
      tolerations:
        - effect: NoSchedule
          key: gpu
          operator: Exists
        - key: "gpu-type"
          operator: "Equal"
          value: 'K80'
          effect: "NoSchedule"
```
