### ISSUE TITLE
Dynamic fanout fanin fails with error

### ISSUE THREAD

**Issue by vikramsg** [argoproj-labs/hera-workflows#193]
Hi, 
I was trying to use the dynamic fanout fanin example, https://github.com/argoproj-labs/hera-workflows/blob/main/examples/dynamic_fanout_fanin.py and I get the following error message, when trying to run it. 

```
    raise ServiceException(http_resp=r)
argo_workflows.exceptions.ServiceException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 15 Jun 2022 15:15:35 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Trailer': 'Grpc-Trailer-Content-Type'})
HTTP response body: {"code":2,"message":"templates.dynamic-fanout.tasks.fanin failed to resolve {{tasks.fanout.outputs.parameters}}"}
```

Any ideas on what might be happening. Does it require a newer Argo installation?

EDIT: The following Argo workflow works, and is similar to what I wanted to do. Is it then a Hera issue?

```
apiVersion: argoproj.io/v1alpha1

kind: Workflow
metadata:
  namespace: argo-data
  generateName: fanin-example
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      Test fanin

spec:
  serviceAccountName: argo
  parallelism: 5

  entrypoint: loop-param-result-example
  templates:
    - name: loop-param-result-example
      steps:
        - - name: generate
            template: gen-number-list
        - - name: write
            template: output-number
            arguments:
              parameters:
                - name: number
                  value: "{{item}}"
            withParam: "{{steps.generate.outputs.result}}"
        - - name: fan-in
            template: fan-in
            arguments:
              parameters:
                - name: numbers
                  value: "{{steps.write.outputs.parameters}}"

    - name: gen-number-list
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          import json
          import sys
          json.dump([i for i in range(20, 31)], sys.stdout)

    - name: output-number
      inputs:
        parameters:
          - name: number
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo {{inputs.parameters.number}} > /tmp/number.txt"]
      outputs:
        parameters:
          - name: number
            valueFrom:
              path: /tmp/number.txt

    - name: fan-in
      inputs:
        parameters:
          - name: numbers
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo received {{inputs.parameters.numbers}}"]
```

**Comment by flaviuvadan** [comment]
Hello @vikramsg! What version of Argo Workflows are you currently running? I tested the example on 3.3.3

**Comment by vikramsg** [comment]
Hi @flaviuvadan unfortunately we are on an older Argo install, 2.12.10. 

But is there any reason why the Argo workflow above should work but not Hera.

**Comment by vikramsg** [comment]
Ok, so I tried to replace the above steps based YAML to a dag based one. And I again encounter an error. I suspect this maybe related. Does the YAML make sense?

```
FATA[2022-06-16T15:33:49.391Z] Failed to submit workflow: templates.loop-param-result-example.tasks.write failed to resolve {{steps.generate.outputs.result}}
```

Below is the YAML. 

```
apiVersion: argoproj.io/v1alpha1

kind: Workflow
metadata:
  namespace: argo-data
  generateName: fanin-example
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      Test fanin

spec:
  serviceAccountName: argo
  parallelism: 5

  entrypoint: loop-param-result-example
  templates:
    - name: loop-param-result-example
      dag:
        tasks:
          - name: generate
            template: gen-number-list
          - name: write
            template: output-number
            depends: generate
            arguments:
              parameters:
                - name: number
                  value: "{{item}}"
            withParam: "{{steps.generate.outputs.result}}"
          - name: fan-in
            template: fan-in
            depends: write
            arguments:
              parameters:
                - name: numbers
                  value: "{{steps.write.outputs.parameters}}"

    - name: gen-number-list
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          import json
          import sys
          json.dump([i for i in range(20, 31)], sys.stdout)

    - name: output-number
      inputs:
        parameters:
          - name: number
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo {{inputs.parameters.number}} > /tmp/number.txt"]
      outputs:
        parameters:
          - name: number
            valueFrom:
              path: /tmp/number.txt

    - name: fan-in
      inputs:
        parameters:
          - name: numbers
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo received {{inputs.parameters.numbers}}"]
```

**Comment by vikramsg** [comment]
And this is what Hera creates with the dynamic fanout fanin example. I can't see any issues as such.  

```
metadata:
  name: fanin-hera0c0fq
spec:
  entrypoint: fanin-hera0c0fq
  parallelism: 5
  service_account_name: argo
  templates:
    - dag:
        tasks:
          - arguments:
              artifacts: []
              parameters: &id001 []
            name: generate
            template: generate
          - arguments:
              artifacts: []
              parameters:
                - name: value
                  value: "{{item.value}}"
            dependencies:
              - generate
            name: fanout
            template: fanout
            with_param: "{{tasks.generate.outputs.result}}"
          - arguments:
              artifacts: []
              parameters:
                - name: values
                  value: "{{tasks.fanout.outputs.parameters}}"
            dependencies:
              - fanout
            name: fanin
            template: fanin
      name: fanin-hera0c0fq
      parallelism: 5
      service_account_name: argo
      steps: []
    - daemon: false
      inputs:
        artifacts: []
        parameters: *id001
      metadata:
        annotations: {}
        labels: {}
      name: generate
      outputs:
        artifacts: []
        parameters: []
      script:
        command:
          - python
        env: []
        env_from: []
        image: container
        image_pull_policy: Always
        name: generate
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
        source: 'import json

          import sys


          # this can be anything! e.g fetch from some API, then in parallel process
          all entities; chunk database records

          # and process them in parallel, etc.

          json.dump([{"value": i} for i in range(10)], sys.stdout)

          '
        volume_mounts: []
      tolerations: []
    - daemon: false
      inputs:
        artifacts: []
        parameters:
          - name: value
            value: "{{item.value}}"
      metadata:
        annotations: {}
        labels: {}
      name: fanout
      outputs:
        artifacts: []
        parameters:
          - name: fanout
            value_from:
              path: /tmp/number
      script:
        command:
          - python
        env: []
        env_from: []
        image: container
        image_pull_policy: Always
        name: fanout
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
        source:
          "import json\ntry: value = json.loads('''{{inputs.parameters.value}}''')\n\
          except: value = '''{{inputs.parameters.value}}'''\n\nprint(f\"Received value:\
          \ {value}!\")\nwith open(\"/tmp/number\", \"w\") as f:\n    f.write(str(value))\n"
        volume_mounts: []
      tolerations: []
    - daemon: false
      inputs:
        artifacts: []
        parameters:
          - name: values
            value: "{{tasks.fanout.outputs.parameters}}"
      metadata:
        annotations: {}
        labels: {}
      name: fanin
      outputs:
        artifacts: []
        parameters: []
      script:
        command:
          - python
        env: []
        env_from: []
        image: container
        image_pull_policy: Always
        name: fanin
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
        source: 'import json

          try: values = json.loads(''''''{{inputs.parameters.values}}'''''')

          except: values = ''''''{{inputs.parameters.values}}''''''


          print(f"Received values: {values}!")

          '
        volume_mounts: []
      tolerations: []
  volume_claim_templates: []
  volumes: []
```
