### ISSUE TITLE
Dynamically mapping Task inputs to Artifact fields

### ISSUE THREAD

**Issue by Trollgeir** [argoproj-labs/hera-workflows#204]
I'm trying to rewrite some yml-files to hera, and I've stumbled upon some issues related to mapping an input variable (a google cloud storage file path) to the parameters of an `InputArtifact` (`GCSArtifact`). 

In the yml-workflow this is done by templating:
```yml
inputs:
    parameters:
      - name: bucket
      - name: filename
    artifacts:
      - name: file
        path: /file_to_process
        gcs:
          bucket: '{{inputs.parameters.bucket}}'
          key: '{{inputs.parameters.filename}}'
```

What's the intended way to use Hera to accomplish this? Should I include templating in the artifact fields, like this?
```python
GCSArtifact(name="file", 
            path="/file_to_process",
            bucket='{{inputs.parameters.bucket}}', 
            key='{{inputs.parameters.filename}}')
```

I'm asking primarily because I've yet to see any templating in the examples.
