### ISSUE TITLE
Dynamic fanout fanin example failed with permission problem

### ISSUE THREAD

**Issue by lamhoangtung** [argoproj-labs/hera-workflows#249]
## Problems

Hi. I'm trying to run the [dynamic_fanout_fanin.py](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/dynamic_fanout_fanin.py) example on a local cluster but the generate step is failing with this error log:
```
Error (exit code 1): pods "dynamic-fanout-fanin-2-268573311" is forbidden: User "system:serviceaccount:default:default" cannot patch resource "pods" in API group "" in the namespace "default"
```
![image](https://user-images.githubusercontent.com/26834698/188826212-0d8db2e1-e635-4ef2-a625-725b87088add.png)

## To replicate
To replicate this problem:
1. Install [`minikube`](https://minikube.sigs.k8s.io/docs/) version v1.26.1, then create a local cluster
```bash
minikube start --cpus 12 --memory 13312
```
2. Install agro workflows version v3.3.9, according to [this](https://argoproj.github.io/argo-workflows/quick-start/) 
```bash
kubectl create namespace argo
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.3.9/install.yaml
kubectl patch deployment \
  argo-server \
  --namespace argo \
  --type='json' \
  -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/args", "value": [
  "server",
  "--auth-mode=server"
]}]'
```
3. Port-forward the agro workflow server:
```bash
kubectl -n argo port-forward deployment/argo-server 2746:2746
```
4. Install `hera-workflows` version 3.7.0 to run the dynamic_fanout_fanin example: 
```bash
pip install hera-workflows==3.7.0
wget https://github.com/argoproj-labs/hera-workflows/raw/main/examples/dynamic_fanout_fanin.py
```
Then change the host and token to: `WorkflowService(host='https://localhost:2746', token="")` and run:
```bash
python dynamic_fanout_fanin.py
```
The problem above should be replicated now.

##
Are there any thing that I might be doing wrong here ? Thanks for checking by!

**Comment by flaviuvadan** [comment]
Thanks for the note @lamhoangtung! The 3.3.9 YAML you linked creates a role called `argo-role`. That role has the following access associated with it: 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-role
  namespace: argo
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
```
This role is bound to the argo service account, which is linked to the deployment, and that one controls what the task can do. You will need to adjust the permissions of the `argo-role` to allow it to patch pods!

**Comment by lamhoangtung** [comment]
Thanks for helping @flaviuvadan. Here is how I resolved this:
1. First create this `fix_role.yml` file with this content:
```yml
# give our webhook ap (as default:default) permissions to create workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-invocation
  namespace: argo
rules:
- apiGroups:
  - "argoproj.io"
  resources:
  - "workflows"
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-default-invocation
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-invocation
subjects:
- kind: ServiceAccount
  name: default
  namespace: default


# give workflows (as argo:default) permissions to run things
# see https://github.com/argoproj/argo/blob/master/docs/workflow-rbac.md
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow
  namespace: argo
rules:
# pod get/watch is used to identify the container IDs of the current pod
# pod patch is used to annotate the step's outputs back to controller (e.g. artifact location)
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
# logs get/watch are used to get the pods logs for script outputs, and for log archival
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-default-workflow
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo
```
2. Then apply it with: `kubectl apply -f fix_role.yml`
3. Now modify the `Workflow` to make sure it run inside the `argo` namespace and the problem should be resolve
