### ISSUE TITLE
Ordering keys in the yaml dump

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera-workflows#378]
When using the `to_yaml` function of Workflows, it results in unnatural ordering, in particular relating to `Task` objects

```py
with Workflow(
   ...
) as w:
    a = Task(
        name="entrypoint",
        command=["python", "-c"],
        args=["print('Hello, a!')"],
    )

w.to_yaml()
```

Gets yaml for the `entrypoint` task template:
```yaml
  templates:
  - container:
      args:
      - print('Hello, a!')
      command:
      - python
      - -c
      image: python:3.7
    name: entrypoint
```
Where `name` comes after the `container` definition. Is there a way or could we add some way to manually order the yaml spec?
