### ISSUE TITLE
Customized entrypoint in workflow-templates

### ISSUE THREAD

**Issue by Gammal-Skalbagge** [argoproj-labs/hera-workflows#445]
Hi,
Currently there seems to be no support for defining entrypoint inside of workflow-template making it impossible to render DAG template inside of workflow-template without reference to it in form of task.
While referring to the DAG in on_exit() automatically renders the template without need to referring to it as to the task, we would like to be able to do the same with entrypoint in workflow-template – to customize entrypoint without need to define a task outside of dag for this purpose. We think it is limiting in terms of workflowTeplateRef usage – it forces user to define another layer of inputs and workflow template arguments to be passed to actual DAG template inside of entrypoint task.

```
from hera import DAG, Parameter, Task, WorkflowTemplate, TemplateRef


with WorkflowTemplate("parallel-dag",  parameters=[Parameter("instruction", "42")]) as wf:
    with DAG("build", inputs=[Parameter("instruction", default="{workflow.parameters.instruction}")], outputs=[Parameter("instruction")]) as published:
        t1 = Task("create", inputs=[published.get_parameter("instruction")], template_ref=TemplateRef(name="hera-workflow-templates", template="coin-flip"))
        t2 = Task("wrap", inputs=[t1.get_result_as("product")], template_ref=TemplateRef(name="hera-workflow-templates", template="coin-flop"))
        t1 >> t2
        published.outputs = [t2.get_result_as("output")]

    with DAG("cleanup", inputs=[Parameter("demo-mode", default="{workflow.parameters.demo-mode}")], outputs=[Parameter("demo-mode")]) as merged:
        t1 = Task("cleanup", inputs=[merged.get_parameter("demo-mode")], template_ref=TemplateRef(name="hera-workflow-templates", template="clenup"))
        merged.outputs = []

    t1 = Task("entry-point", dag=published, inputs=[wf.get_parameter("instruction")] )
    wf.on_exit(merged)

wf.create()
```
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: parallel-dag
spec:
  entrypoint: parallel-dag
  templates:
  - name: parallel-dag
    dag:
      tasks:
      - name: entry-point
        arguments:
          parameters:
          - name: instruction
            value: "{{workflow.parameters.instruction}}"
          - name: instruction
            value: "{{item}}"
        template: build
  - name: build
    dag:
      tasks:
      - name: create
        arguments:
          parameters:
          - name: instruction
            value: "{{inputs.parameters.instruction}}"
        templateRef:
          name: hera-workflow-templates
          template: coin-flip
          clusterScope: false
      - name: wrap
        arguments:
          parameters:
          - name: product
            value: "{{tasks.create.outputs.result}}"
        depends: create
        templateRef:
          name: hera-workflow-templates
          template: coin-flop
          clusterScope: false
    inputs:
      parameters:
      - name: instruction
        default: "{workflow.parameters.instruction}"
    outputs:
      parameters:
      - name: output
        valueFrom:
          parameter: "{{tasks.wrap.outputs.result}}"
  - name: cleanup
    dag:
      tasks:
      - name: cleanup
        arguments:
          parameters:
          - name: demo-mode
            value: "{{inputs.parameters.demo-mode}}"
        templateRef:
          name: hera-workflow-templates
          template: clenup
          clusterScope: false
    inputs:
      parameters:
      - name: demo-mode
        default: "{workflow.parameters.demo-mode}"
  arguments:
    parameters:
    - name: instruction
      value: '42'
  onExit: cleanup


```

We want to acheive this instead:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: parallel-dag
spec:
  entrypoint: build
  templates:
  - name: build
    dag:
      tasks:
      - name: create
        arguments:
          parameters:
          - name: instruction
            value: "{{inputs.parameters.instruction}}"
        templateRef:
          name: hera-workflow-templates
          template: coin-flip
          clusterScope: false
      - name: wrap
        arguments:
          parameters:
          - name: product
            value: "{{tasks.create.outputs.result}}"
        depends: create
        templateRef:
          name: hera-workflow-templates
          template: coin-flop
          clusterScope: false
    inputs:
      parameters:
      - name: instruction
        default: "{workflow.parameters.instruction}"
    outputs:
      parameters:
      - name: output
        valueFrom:
          parameter: "{{tasks.wrap.outputs.result}}"
  - name: cleanup
    dag:
      tasks:
      - name: cleanup
        arguments:
          parameters:
          - name: instruction
            value: "{{inputs.parameters.instruction}}"
        templateRef:
          name: hera-workflow-templates
          template: clenup
          clusterScope: false
    inputs:
      parameters:
      - name: instruction
        default: "{workflow.parameters.instruction}"
  onExit: cleanup

```
