### ISSUE TITLE
Infer imports from the given `source` inside `Script`

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera-workflows#511]
Right now users have to add imports inside the function that is passed as `source` in `Script`. It would be amazing if `Script` would infer and construct the necessary imports for a given `source`. This can likely be a combination of `inspect` + `ast`

**Comment by elliotgunton** [comment]
I tried playing around with `ast` to see how possible this is and whether it's worth investing time in. I found it's possible to do it fairly reliably (for imports alone). I then tried adding global params which is also possible, but we would need to sort by line number (i.e. statement order) to avoid edge cases with the imports. However there was also a problem with a simple assignment within the function messing up the generated `source` (`df` was repeated, and references `s` before it is assigned).

The problems I can foresee are the complexities with the sprawling features and edge cases. e.g. already just adding global params adds some complexity, and I can see users wanting to use functions and classes defined outside of the script function scope, but within the same file. However, I'd be happy to add just import-inferring for now and see how it goes down in the community.


Example:

```py
import re  # plain import
import re as regex  # aliased import

SOME_IMPORTED_GLOBAL = "TO BE SHADOWED BY IMPORT"  # needs to maintain ordering to be before imports

import pandas as pd  # third party
import tests.helper  # dot-import
from tests.helper import ARTIFACT_PATH as SOME_IMPORTED_GLOBAL  # alias + dot-import

from hera.workflows import InlineScriptConstructor, Workflow, script  # workflow-construction imports should be ignored

GLOBAL_PARAM = "test"
MY_ADAPTED_PARAM = SOME_IMPORTED_GLOBAL + "/longer/path"

@script(constructor=InlineScriptConstructor(infer_imports=True))
def hello(s: str):
    df = pd.DataFrame({s: 1, "b": 2})
    print(df)
    print(regex.match(GLOBAL_PARAM, s))
    print(re.match(GLOBAL_PARAM, s))
    print(SOME_IMPORTED_GLOBAL)
    print(MY_ADAPTED_PARAM)
    print(tests.helper.ARTIFACT_PATH)
    print("Hello, {s}!".format(s=s))


with Workflow(
    generate_name="hello-world-",
    entrypoint="hello",
    arguments={"s": "world"},
) as w:
    hello()

```

Produces YAML:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: hello
  templates:
  - name: hello
    inputs:
      parameters:
      - name: s
    script:
      image: python:3.9
      source: |-
        import re
        import re as regex
        import pandas as pd
        import tests.helper
        from tests.helper import ARTIFACT_PATH as SOME_IMPORTED_GLOBAL
        df = pd.DataFrame({s: 1, "b": 2})
        MY_ADAPTED_PARAM = SOME_IMPORTED_GLOBAL + "/longer/path"
        GLOBAL_PARAM = "test"
        SOME_IMPORTED_GLOBAL = "TO BE SHADOWED BY IMPORT"
        import os
        import sys
        sys.path.append(os.getcwd())
        import json
        try: s = json.loads(r'''{{inputs.parameters.s}}''')
        except: s = r'''{{inputs.parameters.s}}'''

        df = pd.DataFrame({s: 1, 'b': 2})
        print(df)
        print(regex.match(GLOBAL_PARAM, s))
        print(re.match(GLOBAL_PARAM, s))
        print(SOME_IMPORTED_GLOBAL)
        print(MY_ADAPTED_PARAM)
        print(tests.helper.ARTIFACT_PATH)
        print('Hello, {s}!'.format(s=s))
      command:
      - python
  arguments:
    parameters:
    - name: s
      value: world
```

---

Appendix: Throwing the code here (rather than a PR) as it can be done with a single function, it just needs one `infer_imports` new attribute on `InlineScriptConstructor`. In fact, users can already achieve this by subclassing `InlineScriptConstructor` and adapting `generate_source`.

We then replace https://github.com/argoproj-labs/hera/blob/0d283df3b2f5ced7a940171c15dfac34c90a4cb6/src/hera/workflows/script.py#L813-L815 with

```py
        s = "\n".join(content[i + 1 :])
        script += textwrap.dedent(s)
        script = textwrap.dedent(script)

        if self.infer_imports:
            imports, globals_ = _get_required_imports_and_globals(instance.source)
            script_body = "\n".join(imports) + "\n"
            script_body += "\n".join(globals_.values()) + "\n"
            script = script_body + script

        return script
```

POC function:

```py
def _get_required_imports_and_globals(fn: Callable) -> Tuple[List[str], Dict[str, str]]:
    module = inspect.getmodule(fn)
    if not module:
        return [], {}

    source = inspect.getsource(module)
    tree = ast.parse(source)

    # 1. Collect top-level imports
    class ImportCollector(ast.NodeVisitor):
        def __init__(self):
            self.imports: Dict[str, Optional[str]] = {}

        def visit_Import(self, node):
            for alias in node.names:
                name = alias.asname or alias.name
                self.imports[name.split(".")[0]] = ast.get_source_segment(source, node)

        def visit_ImportFrom(self, node):
            for alias in node.names:
                name = alias.asname or alias.name
                self.imports[name.split(".")[0]] = ast.get_source_segment(source, node)

    # 2. Collect top-level assignments
    class GlobalAssignmentCollector(ast.NodeVisitor):
        def __init__(self):
            self.assignments = {}  # name -> full source line

        def visit_Assign(self, node):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    self.assignments[target.id] = ast.get_source_segment(source, node)

        def visit_AnnAssign(self, node):
            if isinstance(node.target, ast.Name):
                self.assignments[node.target.id] = ast.get_source_segment(source, node)

    # 3. Find the function node
    fn_node = next((n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name == fn.__name__), None)
    if not fn_node:
        return [], {}

    # 4. Collect used names in function body
    class UsedNameCollector(ast.NodeVisitor):
        def __init__(self):
            self.names = set()

        def visit_Name(self, node):
            self.names.add(node.id)

        def visit_Attribute(self, node):
            if isinstance(node.value, ast.Name):
                self.names.add(node.value.id)
            self.generic_visit(node)

    import_collector = ImportCollector()
    import_collector.visit(tree)

    assignment_collector = GlobalAssignmentCollector()
    assignment_collector.visit(tree)

    usage = UsedNameCollector()
    for stmt in fn_node.body:
        usage.visit(stmt)

    # 5. Filter imports and assignments by usage
    used_imports = [
        import_line
        for name, import_line in import_collector.imports.items()
        if name in usage.names and import_line is not None
    ]
    used_globals = {name for name in usage.names if name in assignment_collector.assignments}

    return used_imports, {name: assignment_collector.assignments[name] for name in used_globals}
```
