### ISSUE TITLE
Add support for raw value task parameters

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera-workflows#87]
Some users want to extract pod metadata, such as IP, from a running task and expose it to others. This can be achieved through something like:
```YAML
    arguments:
      parameters:
        - name: port
          value: "5051"  // raw values
        - name: whatever-task-field
          value: "{{steps.TASK.FIELD}}"  // step
```

https://argoproj.github.io/argo-workflows/variables/

Suggestion:
- have an enum with all available variables
- help users by only requesting a specification of the field and task name: ```Whatever(Task.name, Field.IP)``` (sample)
