### ISSUE TITLE
Duplicate tasks when specifying multiple func_params

### ISSUE THREAD

**Issue by mynameisfiber** [argoproj-labs/hera-workflows#98]
When create a task with multiple `func_params` and connecting that task to any other task (whether it has parallelism in it or not) will double the run count of the original parallel task.

A simple example:

```
from hera.task import Task
from hera.workflow import Workflow
from hera.workflow_service import WorkflowService

from spincycle.runner.utils import get_sa_token


def use_secret(a):
    print(a)


# todo: replace the domain and token with your own
namespace = "etl-argo-v3"
token = get_sa_token(
    "default", namespace=namespace, config_file="/home/micha/.kube/config"
)

ws = WorkflowService(
    host="127.0.0.1:2746",
    token=token,
    namespace=namespace,
)
w = Workflow("volume-provision", ws)

t1 = Task(
    "use_secret1",
    use_secret,
    func_params=[{"a": "a"}, {"a": "a2"}],
)
w.add_task(t1)

t2 = Task(
    "use_secret2",
    use_secret,
    func_params=[{"a": "a"}],
)
t1 >> t2
w.add_task(t2)

ws.submit(w.workflow, namespace=namespace)
```

If you run and submit that, things will look fine within the argo UI:

![image](https://user-images.githubusercontent.com/47370/154320742-f1d5cd5d-3b1b-43b0-a7cd-f6b0e1d2c204.png)

However, if you look at the logs you see that in fact there were 4 pods run for `use-secret1`, two for each parameter choices:

```
Name:                volume-provision-3ab82d9e
Namespace:           etl
ServiceAccount:      default
Status:              Succeeded
Conditions:          
 PodRunning          False
 Completed           True
Created:             Wed Feb 16 18:19:19 +0100 (3 minutes ago)
Started:             Wed Feb 16 18:19:19 +0100 (3 minutes ago)
Finished:            Wed Feb 16 18:19:39 +0100 (3 minutes ago)
Duration:            20 seconds
Progress:            5/5
ResourcesDuration:   8s*(1 cpu),1m26s*(100Mi memory)

STEP                          TEMPLATE                   PODNAME                               DURATION  MESSAGE
 ✔ volume-provision-3ab82d9e  volume-provision-3ab82d9e                                                    
 ├─✔ use-secret1(0:a:"a")     use-secret1                volume-provision-3ab82d9e-940572814   4s          
 ├─✔ use-secret1(0:a:\"a\")   use-secret1                volume-provision-3ab82d9e-4054141412  5s          
 ├─✔ use-secret1(1:a:\"a2\")  use-secret1                volume-provision-3ab82d9e-4279694763  4s          
 ├─✔ use-secret1(1:a:"a2")    use-secret1                volume-provision-3ab82d9e-3966846017  4s          
 └─✔ use-secret2              use-secret2                volume-provision-3ab82d9e-1375103652  4s          
```

I've been trying to debug why this is happening but I can't seem to get anywhere. Taking out the `use-secret2` task or removing the parallelism for `use-secret1` leads to the expected number of tasks being run. A notable thing I've found is that the parallel task is always doubled in the number of tasks, no matter how parallel it's dependencies are. Also, the difference in quote-escaping between the original and duplicate tasks is consistent across all the times I've seen this happening... I presume it's a clue but I'm unsure where to trace it back to.

For reference, the template that is created is:

```
- name: volume-provision-3ab82d9e
  inputs: {}
  outputs: {}
  metadata: {}
  dag:
    tasks:
      - name: use-secret1
        template: use-secret1
        arguments:
          parameters:
            - name: a
              value: '{{item.a}}'
        withItems:
          - a: '"a"'
          - a: '"a2"'
      - name: use-secret2
        template: use-secret2
        arguments:
          parameters:
            - name: a
              value: '"a"'
        dependencies:
          - use-secret1
  parallelism: 50
- name: use-secret1
  inputs:
    parameters:
      - name: a
        value: '{{item.a}}'
  outputs: {}
  metadata: {}
  daemon: false
  script:
    name: use-secret1
    image: 'python:3.7'
    command:
      - python
    resources:
      limits:
        cpu: '1'
        memory: 4Gi
      requests:
        cpu: '1'
        memory: 4Gi
    source: |
      import json
      a = json.loads('{{inputs.parameters.a}}')

      print(a)
- name: use-secret2
  inputs:
    parameters:
      - name: a
        value: '"a"'
  outputs: {}
  metadata: {}
  daemon: false
  script:
    name: use-secret2
    image: 'python:3.7'
    command:
      - python
    resources:
      limits:
        cpu: '1'
        memory: 4Gi
      requests:
        cpu: '1'
        memory: 4Gi
    source: |
      import json
      a = json.loads('{{inputs.parameters.a}}')

      print(a)
```
